<h4><?php echo $this->title; ?></h4>

<table cellpadding='3' cellspacing='5'>


	<tr>
		<td><a
			href="<?php echo $this->url(array('controller'=>'report', 
            'action'=>'prize'));?>">Complete Program</a></td>
	</tr>



	<tr>
		<th>Other Printables:</th>
	</tr>
	<tr>
		<td><a
			href="<?php echo $this->url(array('controller'=>'report', 
            'action'=>'pointcards'));?>">Print Point Cards</a></td>
	</tr>

	<tr>
		<td><a
			href="<?php echo $this->url(array('controller'=>'report', 
            'action'=>'account'));?>">Print Team Accounts</a></td>
	</tr>
	<tr>
		<td><a
			href="<?php echo $this->url(array('controller'=>'report', 
            'action'=>'horsedraw'));?>">Print Horse Draw Sheets</a></td>
	</tr>

	<tr>
		<td><a
			href="<?php echo $this->url(array('controller'=>'report', 
            'action'=>'judgescards'));?>">Print Judge's Cards</a></td>
	</tr>



</table>




