<h3>
<?php echo "Service Terms"; ?>
<div id='terms' style="background-color:olive;">
</h3>

<ul>

<li>
This software is free for IHSA members (Intercollegiate Horse Show Association).
</li>
<li>
To become eligible for using the software, you must register.
You agree to provide accurate information when you register.
</li>
<li>
You agree to provide feedback by filling out the contact form every time when you create a show.
</li>
<li>
You agree to tell at least two other people about this software.
</li>
<li>If you find a bug, you agree to report it  immediately by filling out the contact form.</li>
<li>
If you do not like the formatting in the pdf reports, 
you are allowed to copy and paste the content into a Word document or such, 
provided that you include this phrase in a visible place on your new report:
 'This document was modified from its original version provided by Veni,Vidi, Vici!
</li>
<li>
You will not try to break the software on purpose.
</li>
<li>
This software comes with ABSOLUTELY NO WARRANTY. 
</li>
<li>
This web site may shut down without any notice.
</li>
<li>
You can accept the terms  either explicitly by clicking "I agree", or checking the checkbox, or 
implicitly by actually using the software.
</li>
</ul>

<br></br>
</div>