<table cellpadding="3" cellspacing="2" width="70%" align="center">
<tr><td><h1><?= $this->title?></h1></td></tr>
<?php foreach ($this->teams as $team) :?>
<?php if (count($team->riders) > 0) : ?>
	<tr bgcolor='yellow'>
		<th><?= $team->teamname; ?> &nbsp; &nbsp;
		<a href="<?php echo $this->baseUrl() . '/report/myaccount/team/' . $team->teamid;?>">Team Account</a></th>
	</tr>
	<?php $cnt = 0;  foreach ($team->riders as $rider) : ?>
	<tr>
		<td><?php $cnt++; echo $cnt . '. ' . $rider->ridername . ': ' . $rider->classes; ?></td>
	</tr>
	<?php endforeach;?>

	<?php endif;?>
	<?php endforeach;?>

</table>


