<?php $form = $this->form; 
$showname = $form->SHOW_NAME;
$showdate = $form->SHOW_DATE;
$eventtype = $form->EVENT_TYPE_ID;
$submit = $form->submit;
$trigger = $form->triggerButton;
?>

<form id="show" enctype="application/x-www-form-urlencoded" action="" method="post">
<input type="hidden" name="SHOW_ID" value="" id="SHOW_ID" />

<input type="hidden" name="OWNER_ID" value="" id="OWNER_ID" />
<table>
<tr>
<th><label for="SHOW_NAME" class="required">Show Name</label></th>
<td><input type="text" name="SHOW_NAME" id="SHOW_NAME" value="" /></td>
</tr>
<tr>
<th><label for="SHOW_DATE" class="required">Show Date</label></th>
<td><input type="text" name="SHOW_DATE" id="SHOW_DATE" value="" />
<button name="triggerButton" id="triggerButton" type="button">...</button></td>
</tr>
<tr>
<th><label for="EVENT_TYPE_ID" class="required">Show Type</label></th>
<td><select name="EVENT_TYPE_ID" id="EVENT_TYPE_ID">
    <option value="" label="--Select One--" selected="selected">--Select One--</option>
    <option value="1" label="Hunter seat show">Hunter seat show</option>
    <option value="2" label="Western show">Western show</option>
</select></td>
</tr>
<tr>
<th></th>
<td>
<input type="submit" name="submit" id="submitbutton" value="Add" /></td>
</tr>
</table>

</form>