<table cellspacing="10" cellpadding="10">
<tr><td>
<h1>Users guide</h1>
<h4>Typical Scenario</h4>
You are setting up an IHSA show competition. 
Teams and students have been entered and now you need
to split the classes and print the show program and entry list.
You can easily do this with the Veni,Vidi,Vici! program.

<h4>Purpose</h4>
<p>
The purpose of this software is to facilitate collaboration between the teams
participating in an IHSA competition.
In the IHSA competition style, the show host provides the horses, 
and the horses are assigned to the riders by random drawing just before the
competition.

The intended users of this software therefore are primarily 
IHSA show secretaries, and coaches of the participating teams.
This software allows you to setup a show, and enter teams and riders,
and their class entries, split classes, and finally print the show program.


</p>

<h4>Teams and Studens Info</h4>
<p>


The class names are predefined based on the IHSA rule book for Hunter seat
and Western shows. You cannot add or change class names, or show types.
When you initially login, there will be only two things you can do:
setup a show, or enter teams. Only after entering the teams, you can enter
students .

After entering the students info, 
you can add their entries to the show and add back numbers.
</p>
<h4>Class splits, Show Program and Teams List</h4>
<p>
As soon as some entries exist, you can generate and print two reports: 
Team List and Show Program. You can indicate how many split classes for each class.
The Show Program includes the total number of entries at the bottom.
The Team List includes subtotal riders and entries for each team. 

</p>
<h4>Deleting Records</h4>
<p>
If you uncheck all classes for a student, it will erase her back number also.
if you delete a student, it will delete her entries from <em>all</em> shows.
If you delete a team, it will delete all it's students, and all their
entries from all shows.
If you delete a show, it will delete all the entries from that show, but
it will not delete the teams and students names.
</p>

<h4>Multiple shows</h4>
<p>
If you setup more than one show, the most recent show will be assumed current,
but you can change this by selecting another show from the grid.
</p>

<p>
Each user can view and edit only his data. Nobody can use shows, 
teams and riders entered by other users.
</p>
</td></tr>
</table>