<br>
<p>
You can use this program <em>free</em> of charge and with no strings attached. 
Donations are welcome but not required. 
</p>

<h4>Different ways you can support this site:</h4>

<li>Tell a friend about this program</li>
<li>Tell us how to improve the program </li>
<li>Come for another visit! </li>
<li>Visit our sponsors (only if you'd like)</li>
<li>Make a donation (only to the extent you can afford)</li>
<br></br>
<br></br>




